### ISSUE TITLE
possible in inflector / class_map systems

### ISSUE THREAD

**Issue by odigity** [jeremyevans/fixture_dependencies#13]
Test case:  https://github.com/odigity/fd_test_case

    $ bundle
    $ ./migrate
    $ ./foo.rb

I get:

    root@5964674eb6da:/tmpdev# ./foo.rb 
    /usr/local/bundle/gems/sequel-4.27.0/lib/sequel/extensions/inflector.rb:142:in `constantize': uninitialized constant PorcIo (NameError)
	from /usr/local/bundle/gems/sequel-4.27.0/lib/sequel/extensions/inflector.rb:142:in `module_eval'
	from /usr/local/bundle/gems/sequel-4.27.0/lib/sequel/extensions/inflector.rb:142:in `constantize'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:130:in `model_class'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:151:in `use'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:221:in `block in use'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:185:in `each'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:185:in `use'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:46:in `block in load'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:43:in `map'
	from /usr/local/bundle/gems/fixture_dependencies-1.6.0/lib/fixture_dependencies.rb:43:in `load'
	from ./foo.rb:42:in `<main>'

**Comment by jeremyevans** [comment]
The issue here is when using class_map with namespaced models, you need to use the model's full underscored path.  It may be helpful to add both the full underscored path and the base underscored path.  Here's an example of a fix that appears to work: http://pastie.org/10463145
