### ISSUE TITLE
Ability to load attributes only

### ISSUE THREAD

**Issue by badosu** [jeremyevans/fixture_dependencies#14]
Feel free to close this issue, this is mostly to communicate a feature request and/or orientation on how to send a patch for this. If this medium is not adequate, let me know where we can discuss.

The ability to load only the attributes of a fixtures, their dependencies can be created no problem, but the last step that would be to insert the actual record would not be performed, and would return only the record before saving.

This is very useful for testing multiple different scenarios where small attribute mutations are performed on a record, and where creating the records manually is contraproductive compared to using the fixtures.

A suggestion would be to use `#build` to load the unsaved record and optionally expose a `#load_attributes` to load a hash of the attributes.

Let me know your thoughts on this.

**Comment by jeremyevans** [comment]
This medium is fine.  For my projects that lack an external forum for help, opening GitHub issues is the best way to get support.

Your idea sounds fine to me. Please submit a pull request for it, with the usual provisos (don't break any existing behavior, add specs and documentation).  I think you'd probably want to add something to the README as well about this.  Note that ruby 1.8.7 is still supported by this project, so don't use ruby 1.9+ features.

**Comment by badosu** [comment]
I did some experimentation on this area and the first approach, that would be to split the '#use' method into 2 parts was successful.

There's a problem though, because the 2 methods share a lot of state, and performing this simplistic approach would create a horrendous method signature for the second part:

`def save(record, obj, mtype, loading, spaces, model_name, name, fpk, procs, many_associations)`

The alternative would be to reduce these parameters to the ones I can extract from the record, however that would imply in a performance decrease;
