### ISSUE TITLE
Compatibility with Rails 4.2?

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/fixture_dependencies#19]
Any tips on wiring up fixture_dependencies to work with Rails 4.2's ActiveSupport::TestCase and Sequel? It appears to be Minitest-based. Thanks in advance!

**Comment by jeremyevans** [comment]
You probably want to look at the `lib/fixture_dependencies/{minitest_spec,test_unit}/*.rb` files and use something similar to that.  `lib/fixture_dependencies/test_unit/sequel.rb` is probably closest, you may need to just adjust the super class in that one.

**Comment by jeremyevans** [comment]
Hopefully that tip was sufficient.  I'm going to close this now, if you are still having problems, please respond.
