### ISSUE TITLE
Support for JSON/JSONB fields

### ISSUE THREAD

**Issue by chrisnicola** [jeremyevans/fixture_dependencies#20]
I'm currently in the process of migrating some AR stuff to Sequel and noticed that the values for JSON fields don't seem to be supported out of the box. Is there a way to do this?

**Comment by jeremyevans** [comment]
Without an example of what you are trying to do, I'm not exactly sure.  If you are using the pg_json extension in your Database and your fixture yaml file has an array or hash value for the column, I assume it would work, but I haven't actually tried it.

If you can't get it to work, can you please submit a small, self contained example showing the problem so I can debug?

**Comment by chrisnicola** [comment]
In ActiveRecord you can define a `store_accessor` on a JSON or JSONB field and then define fixtures as such.

```
fixture:
  attribute: 'string'
  json_properties:
    property_one: 10
    property_two: 'name'
```

Where `json_properties` is a JSON(B) fields on this table and it will insert `property_one` and `property_two` in that field as JSON.

**Comment by jeremyevans** [comment]
If your column name is `json_properties`, and your Sequel::Database instance loads the pg_json extension before you create your model classes, that may work, as the setter method should accept a hash.  If not, as mentioned earlier, please provide a small, self contained example so I can debug.

**Comment by chrisnicola** [comment]
Thanks I played around with it a bit more and I was not applying the `pg_json` extension in the right place which was causing my problems. Thanks so much for your help. Sorry to be such a bother.
