### ISSUE TITLE
Does not seem to respect namespace casing

### ISSUE THREAD

**Issue by chrisnicola** [jeremyevans/fixture_dependencies#21]
All of my code is namespaces including my models. An example is as such:

```
module API
  module Models
    class Referral < Sequel::Model(:referrals)
      many_to_one :referrer, class: :User, class_namespace: 'API::Models'
      many_to_one :referree, class: :User, class_namespace: 'API::Models'
    end

    FixtureDependencies&.class_map[:referrals] = API::Models::Referral
  end
end
```

As you can see to support testing I have to update the `class_map`. I also have to add the `class_namespace`. This feels a bit redundant, in fact both seem like they should be unnecessary since the models are all in the same namespace I would probably expect them to look up in that module space by default.

Now then this code will work:

```
user = API::Models::User.create()
referral = API::Models::Referral.create(referrer: user)
```

But when I try to create a fixture in `referrals.yml` like this:

```
referral:
  referrer: user
  rewarded: false
```

```
@referral = load(:referrals__referral)
```

I get an error:

```
LoadError: Unable to autoload constant Api, expected /User/chrisnicola/src/project/lib/api.rb to define it
```

It seems to be an issue with inflection happening.

**Comment by jeremyevans** [comment]
The issue with :class looking in the root namespace is just how Sequel works, it's not related to fixture dependencies.  It can't be changed due to backwards compatibility.  It was the reason that :class_namespace was introduced in Sequel.

The Sequel association options are unrelated to fixture dependencies class_map.  It may not be perfectly DRY, but I don't think much can be done to fix that without breaking backwards compatibility.

I'm not sure why you are getting the LoadError you are getting.  Fixture dependencies does not use autoload, so it might be related to something else in your environment (avoid using autoload if possible). Fixture dependencies might be referencing Api instead of API because it calls camelize, but if the class_map includes the correct entries, it shouldn't.  One simple fix may be: `Api = API`, or to fix String#camelize to generate `API` instead of `Api`.

Anyway, if you continue to have problems with this, please submit a small, self contained example showing the issue so I can debug.

**Comment by chrisnicola** [comment]
Thanks @jeremyevans. On the first note, I'm wondering if a plugin could be written to support looking in the current namespace? I'd be happy to look into this, just wondering if it has already been considered and dismissed?

The autoload error I'm getting is because I'm running under a Rails environment. I would definitely avoid using it, but currently this isn't possible. The plan in the near future is to extract ourselves from Rails though.

`Api = API` isn't a bad solution in the short term and I managed to get it working this way. Though it definitely seems to me there is something funny going on where it isn't actually looking dependencies up using the class map but it does work for the original `load` entry. If I don't have a dependency in the fixture it works without the `Api = API` assignment, but with the dependency it fails when loading that dependency. Perhaps it is re-camelizing the value? I'll try to create a more trivial solution we can debug from as this information probably isn't helping much.

Also noticed I was getting the inflections wrong (man I hate inflections). Just to confirm, for the fixture files it is plural, but in the `class_map` it needs to be singular, as well when calling `load(referral__referral)` it is singular. Do I have that right? (Also is there a way to disable using inflections for finding the fixtures, I assume that was done for compatibility with AR fixtures?)

**Comment by jeremyevans** [comment]
You can set `Sequel::Model.default_association_options[:class_namespace] = 'API::Models'` if you want to set the default for all associations that use the `:class` option, so I don't think a plugin would be necessary.

Fixture filenames use the table name, which can be singular or plural depending on your database schema.  class_map and load use the singular form of the model name, correct.  If you can't create a self contained example, even a backtrace from the error raised by fixture dependencies would be helpful so I can see where the problem is.

**Comment by chrisnicola** [comment]
Thanks that does simplify things. I still need to add everything to the class map.

I'll work on a simple example of the API vs Api issue.

The other thing I'd like to find a way to address is requiring the `FixtureDependencies.class_map` redundancy with the namespaces.

I wonder if it would be possible to have something similar to `default_association_options` for `FixtureDependencies`. Alternatively I might be able to hook into inheritance of `Sequel.Model(:table_name)` to set the `class_map` via a plugin of some sort.

**Comment by jeremyevans** [comment]
You can load the subclasses plugin into Sequel::Model before creating your model classes, then use it to go through each subclass and update the class_map.  Or you could use ObjectSpace to find all Sequel::Model subclasses in the namespace you care about and update the class_map with those.  If you are only doing that during testing, it's probably fine.  Both are probably easier than hooking into inheritance (though that isn't too difficult).

**Comment by chrisnicola** [comment]
Thanks that plugin helps. I've added this in the singleton where I bootstrap my Sequel DB connection.

```
      def load_models
        Sequel::Model.plugin :timestamps, update_on_create: true
        Sequel::Model.default_association_options[:class_namespace] = 'API::Models'
        FixtureDependencies&.fixture_path = 'lib/api/models/fixtures'
        Sequel::Model.plugin(:subclasses) { |sc|
          models << sc
          if FixtureDependencies && sc.name
            FixtureDependencies.class_map[singularize(sc.table_name).to_sym] = sc
          end
        }
        require 'api/models'
      end
```

One limitation that I noticed is that the subclasses plugin block doesn't seem to work as well with with models defined like this:

```
class MyModel < Sequel::Model(:table_name)
end
```

This passes returns a `Class` object to the block which doesn't have a `#name` and calling `table_name` on it raises this error: `/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sequel-4.37.0/lib/sequel/model/base.rb:270:in `dataset': No dataset associated with #<Class:0x007f9f3dd23078> (Sequel::Error)`

Hence the check I have on `sc.name` so that doesn't happen. However it also means this won't work for Sequel::Model classes defined in this way. This isn't a big problem for me right now as all my tables are the plural of the class name so I can just inherit from `Sequel::Model`

Anyways this is good enough for me now, I really appreciate your help and all the work that you've put into Sequel among other gems.

**Comment by jeremyevans** [comment]
I'm glad you got everything to work.  It's expected that subclasses also yields anonymous, automatically created classes, so checking the name as you are doing is a good way to handle that.

**Comment by chrisnicola** [comment]
@jeremyevans sure, but in the case where I actually want to add them to the `class_map` how would I get the class name so I can assign it?

**Comment by jeremyevans** [comment]
Via `sc.name`, as you are currently doing.  As I said, the example you gave is a good way to handle things.

**Comment by chrisnicola** [comment]
But `sc.name` is `nil` for the models defined with `Sequel::Model(:table_name)` when I get them.

**Comment by jeremyevans** [comment]
OK, I think what you are saying is if you do `A = Sequel::Model(:table_name)`, then `sc.name` isn't `A` in the block.  That's correct, and how ruby works.  If you do `class A < Sequel::Model(:table_name)`, the block should be called twice, once with the anonymous subclass that is A's superclass, and once with A itself, where sc.name should return `"A"`.

You can probably work around the first issuing by not setting a block when loading the plugin, but calling `Sequel::Model.descendents.each` later.

If I'm missing the point you are trying to get at, I apologize.  Please try to provide a code example in that case, to allow me to better understand.

**Comment by chrisnicola** [comment]
@jeremyevans ah I'm sorry I didn't realize that. So then the code does work just fine. Thanks that helps a lot.
