### ISSUE TITLE
Setting up a "hello world" fixture - "NameError: uninitialized constant Test"

### ISSUE THREAD

**Issue by BKSpurgeon** [jeremyevans/fixture_dependencies#30]
Hi everyone

I am trying to set up a hello world test using a fixture. But even before using the fixture there seems to be error when running the tests. I have a minimal rails app using sequel and minitest to demonstrate and reproduce this issue.

(Am happy to make a PR to improve the documentation to aid in the transition for newcomers migrating from active record to sequel, to help them set things up, once we can get to the bottom of this issue.)

# Minimal App

Here it is: https://github.com/BKSpurgeon/testing_in_sequel

# Steps to reproduce

I am trying to get a 'hello world' sample test working with sequel and minitest using fixtures.

* I have used the sequest_rails gem to get started.
* I have created a `test/sequel_test_case.rb` file which contains:

```ruby
DB = Sequel.postgres 

class SequelTestCase < Minitest::Test
  def run(*args, &block)
    DB.transaction(:rollback=>:always, :auto_savepoint=>true){super}
  end
end
```

Then I created a hello world test in a file I created: `test/models/organisation_test.rb`

```ruby
require 'test_helper'
require 'sequel_test_case'

class OrganisationTest < SequelTestCase
  def test_organisation_name
    assert_equal(true, true) ## This test passes as expected.
  end
end

```

### Adding a fixture

* I have created an Organisation scaffold which has one attribute: nthereame.

The fixture I have created is an `organisation.yml` file located in `text/fixtures/organisation.yml`. 

```yml
one:
  name: MyString

two:
  name: MyString
```

### Setting up the fixture

I went to the `organisation_test.rb` and added the line ` require 'fixture_dependencies/test_unit/sequel'` and I also changed the class from which OrganisationTest was inheriting from:

```ruby
require 'test_helper'
require 'sequel_test_case'

require 'fixture_dependencies/test_unit/sequel'

class OrganisationTest < FixtureDependencies::SequelTestCase
  def test_organisation_name
    organisation = Organisation.new
    assert_equal(organisation, false)
  end
end
```

When I run the test with `bin/rake` an error comes up:

```
Running via Spring preloader in process 18970
rake aborted!
NameError: uninitialized constant Test
/home/koshy/UbuntuHDD/Documents/RailsProjects/testing-sequel/test/models/organisation_test.rb:4:in `<main>'
-e:1:in `<main>'
Tasks: TOP => default => test
```

Not sure how to proceed from here. 

Would appreciate any insight into this issue.

**Comment by jeremyevans** [comment]
You are requiring `fixture_dependencies/test_unit/sequel`, but that is for `test_unit`, not for `minitest` (you appear to be using minitest).  That's the direct reason for the failure.

Fixture dependencies ships with support for `minitest/spec`, but not for `minitest` directly.  You can probably define your own file with the following code, then require that file:

```ruby
require 'fixture_dependencies/helper_methods'

class Minitest::Test
  include FixtureDependencies::HelperMethods
  def run(*args, &block)
    Sequel::Model.db.transaction(:rollback=>:always){super}
  end
end
```

**Comment by BKSpurgeon** [comment]
great thank you Jeremy.

I have a very basic app functioning with: (i) Sequel, (ii) fixtures and (iii) minitest.

Shall I post a link with instructions at the bottom of the page docs page? I have documented the how to on the basic app fairly well i feel that newcomers should have little to no trouble.

**Comment by jeremyevans** [comment]
Sure, if you think it would be helpful, please send in a pull request for that.  I'm going to close this issue since it doesn't appear to be a bug.
